#!/usr/bin/env node
`use strict`
var stvCount = require('./build/all');
var path = require('path');
var fs = require('fs');
var argv = require('minimist')(process.argv.slice(2));
console.dir(argv);

var options = argv.o || argv.options || 'options.json';

options = require(path.join(process.cwd(), options.toString()));

if (argv.blt) {
  stvCount.bltCount(blt, options);
} else if (argv.csv) {
  var csv = fs.createReadStream(path.join(process.cwd(), argv.csv)).pause();
  stvCount.csvCount(csv, options);
} else if (argv.json) {
  var json = require(path.join(process.cwd(), argv.json));
  stvCount.jsonCount(json, options);
} else {
  console.error('Error: no file type indicated')
}
